<a href="https://colab.research.google.com/github/krishnamalani1164/deep-learning-pytorch/blob/main/PyTorch_deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PyTorch Basics:Tensors and Gradients

In [1]:
import torch

#Tensors

###At its core Pytorch is a library for processing tensors. A tensor is a number,vector,matrix or any n-dimensional array.Let's create a tensor with a single number.

In [2]:
#Number
t1 = torch.tensor(4.)
t1

tensor(4.)

## Lets create slightly more complex tensors

In [3]:
#Vector
t2 = torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [4]:
#Matrix
t3 = torch.tensor([[5.,6],[7,8],[9,10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [5]:
#3-dimensional array
t4 = torch.tensor([[[11,12,13],[13,14,15],[15,16,17],[17,18,19]]])
t4

tensor([[[11, 12, 13],
         [13, 14, 15],
         [15, 16, 17],
         [17, 18, 19]]])

### Note:Tensors can have any number of dimensions and different lengths along each dimension.We can inspect the length along each dimension using the .shape property of a tensor

In [6]:
t1.shape

torch.Size([])

In [7]:
t2.shape

torch.Size([4])

In [8]:
t3.shape

torch.Size([3, 2])

In [9]:
t4.shape

torch.Size([1, 4, 3])

#Tensor operations and gradients

In [10]:
#Create tensors.
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad = True)
b = torch.tensor(5., requires_grad = True)

In [12]:
y = w * x + b
y #Computation of tensors is done through .backward

tensor(17., grad_fn=<AddBackward0>)

In [13]:
#Compute derivatives
y.backward()

In [14]:
#Display gradients
print('dy/dx:',x.grad) # Gradients is just an another word for derivative
print('dy/dw:',w.grad)
print('dy/db:',b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


#Introduction to libraries

In [16]:
import numpy as np
x = np.array([[1,2],[3,4.]])
x

array([[1., 2.],
       [3., 4.]])

#### we can covert a numpy array to a pytorch using torch.from_numpy

In [18]:
#Conert the numpy array to a torch tensor
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

#### lets verify that the numpy array and torch tensor have similar data types

In [19]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

#### we can convert a pytorch tensor to a numpy array using .numpy method of a tensor

In [20]:
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])